### PR TITLE
Constant position tracking 

### LINKED ISSUE #14: ## Add constant Location refresh
As a User, 
I want my new position displayed without reloading the page, 
so I constantly know where I am

-[ ] add Interval

Edit: Doesn't need an interval added watch and high accuracy, instead

### PR DESCRIPTION
**Pull request by Marc-Klein**
A little one

## Motivation
- wanted constant position tracking without reloading the page

## Issues closed
close #14

### CODE REVIEW

**Comment by DenSchmi81** [comment]
Seems pretty. LGTM!

**Comment by doemser** [comment]
I can use the +/- buttons to zoom, but shouldnt I be abled to zoom with my mousewheel too?

**Comment by DenSchmi81** [comment]
@doemser Feature kommt noch ;-)

**Comment by Marc-Klein** [comment]
@doemser No Ive disabled it :)

**Pull request merged**
